# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"$\n\x0cProductToAdd\x12\x14\n\x0cname_product\x18\x01 \x01(\t\")\n\x12\x41\x64\x64ProductResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\"+\n\x13ProductExistRequest\x12\x14\n\x0cname_product\x18\x01 \x01(\t\"*\n\x14ProductExistResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"*\n\x12ProductSaleRequest\x12\x14\n\x0cname_product\x18\x01 \x01(\t\"*\n\x13ProductSaleResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32\x90\x01\n\x10ProductInventary\x12=\n\x0cProductExist\x12\x14.ProductExistRequest\x1a\x15.ProductExistResponse\"\x00\x12=\n\x0cWriteProduct\x12\x14.ProductExistRequest\x1a\x15.ProductExistResponse\"\x00\x32\x42\n\x0cStockService\x12\x32\n\nAddProduct\x12\r.ProductToAdd\x1a\x13.AddProductResponse\"\x00\x32I\n\x0bProductSale\x12:\n\x0bSellProduct\x12\x13.ProductSaleRequest\x1a\x14.ProductSaleResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTTOADD._serialized_start=17
  _PRODUCTTOADD._serialized_end=53
  _ADDPRODUCTRESPONSE._serialized_start=55
  _ADDPRODUCTRESPONSE._serialized_end=96
  _PRODUCTEXISTREQUEST._serialized_start=98
  _PRODUCTEXISTREQUEST._serialized_end=141
  _PRODUCTEXISTRESPONSE._serialized_start=143
  _PRODUCTEXISTRESPONSE._serialized_end=185
  _PRODUCTSALEREQUEST._serialized_start=187
  _PRODUCTSALEREQUEST._serialized_end=229
  _PRODUCTSALERESPONSE._serialized_start=231
  _PRODUCTSALERESPONSE._serialized_end=273
  _PRODUCTINVENTARY._serialized_start=276
  _PRODUCTINVENTARY._serialized_end=420
  _STOCKSERVICE._serialized_start=422
  _STOCKSERVICE._serialized_end=488
  _PRODUCTSALE._serialized_start=490
  _PRODUCTSALE._serialized_end=563
# @@protoc_insertion_point(module_scope)
