# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"+\n\x13ProductExistRequest\x12\x14\n\x0cname_product\x18\x01 \x01(\t\"*\n\x14ProductExistResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x32\x90\x01\n\x10ProductInventary\x12=\n\x0cProductExist\x12\x14.ProductExistRequest\x1a\x15.ProductExistResponse\"\x00\x12=\n\x0cWriteProduct\x12\x14.ProductExistRequest\x1a\x15.ProductExistResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTEXISTREQUEST._serialized_start=17
  _PRODUCTEXISTREQUEST._serialized_end=60
  _PRODUCTEXISTRESPONSE._serialized_start=62
  _PRODUCTEXISTRESPONSE._serialized_end=104
  _PRODUCTINVENTARY._serialized_start=107
  _PRODUCTINVENTARY._serialized_end=251
# @@protoc_insertion_point(module_scope)
